### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by fireshaper** [davide-romanini/unrar-cffi#6]
When I try to install I get the error below.

I'm using pip version: pip 20.1.1
And python3 version: Python 3.7.4
Windows Server 2016

```
D:\Mylar>py -m pip install unrar-cffi
Collecting unrar-cffi
  Using cached unrar-cffi-0.1.0a5.tar.gz (253 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-du5dn_xo\\unrar-cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-du5dn_xo\\unrar-cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-pip-egg-info-2sj54yfr'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-du5dn_xo\unrar-cffi\
    Complete output (36 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-du5dn_xo\unrar-cffi\setup.py", line 63, in <module>
        python_requires='>=3.4'
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\dist.py", line 426, in __init__
        k: v for k, v in attrs.items()
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\dist.py", line 717, in finalize_options
        ep(self)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\dist.py", line 724, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "c:\users\admini~1\appdata\local\temp\2\pip-install-du5dn_xo\unrar-cffi\.eggs\cffi-1.14.0-py3.7-win32.egg\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\admini~1\appdata\local\temp\2\pip-install-du5dn_xo\unrar-cffi\.eggs\cffi-1.14.0-py3.7-win32.egg\cffi\setuptools_ext.py", line 57, in add_cffi_module
        ffi = ffi()      # maybe it's a function instead of directly an ffi
      File "buildconf.py", line 77, in create_builder
        preprocess = subprocess.check_output(PREPROCESS_CMD, universal_newlines=True)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by davide-romanini** [comment]
It seems you are using a 32bit python version. To build on travis I only support python 3.7 x86_64. 
32 bit versions seem to be deprecated on chocolatey, so at the moment the only solution is to upgrade to 64bit version of python.
